/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.57
 * Generated at: 2020-10-21 10:38:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/GitRepo/mate/mate/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1601992709208L));
    _jspx_dependants.put("jar:file:/C:/GitRepo/mate/mate/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/GitRepo/mate/mate/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css\" integrity=\"sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4\" crossorigin=\"anonymous\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\" id=\"bootstrap-css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/loginForm.css\" />\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\" integrity=\"sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js\" integrity=\"sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy\" crossorigin=\"anonymous\"></script>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/headerS.jsp", out, false);
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t$('#login-form-link').click(function(e) {\r\n");
      out.write("\t\t\t$(\"#login-form\").delay(100).fadeIn(100);\r\n");
      out.write("\t\t\t$(\"#register-form\").fadeOut(100);\r\n");
      out.write("\t\t\t$('#register-form-link').removeClass('active');\r\n");
      out.write("\t\t\t$(this).addClass('active');\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('#register-form-link').click(function(e) {\r\n");
      out.write("\t\t\t$(\"#register-form\").delay(100).fadeIn(100);\r\n");
      out.write("\t\t\t$(\"#login-form\").fadeOut(100);\r\n");
      out.write("\t\t\t$('#login-form-link').removeClass('active');\r\n");
      out.write("\t\t\t$(this).addClass('active');\r\n");
      out.write("\t\t\te.preventDefault();\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tif(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ not empty snsMember }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tconsole.log(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ NaverMember }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("\t\t\t$(\"#register-form\").delay(100).fadeIn(100);\r\n");
      out.write("\t\t\t$(\"#login-form\").fadeOut(100);\r\n");
      out.write("\t\t\t$('#login-form-link').removeClass('active');\r\n");
      out.write("\t\t\t$(\"#register-form\").addClass('active');\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\r\n");
      out.write("\t\t$(\"#phone-send\").click(function(){\r\n");
      out.write("\t\t\tvar $phone = $(\"#phone\").val();\r\n");
      out.write("\t\t    var popUrl =\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/pCheck.do\";\r\n");
      out.write("\t\t    var popOption = \"width=650px, height=550px, resizable=no, location=no, top=300px, left=300px;\"\r\n");
      out.write("\t\t\tconsole.log($phone);\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/phoneSend.do\",\r\n");
      out.write("\t\t\t\tdata:{\r\n");
      out.write("\t\t\t\t\treceiver: $phone\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\t\tmethod: \"post\",\r\n");
      out.write("\t\t\t\tsuccess: function(data){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\tvar $num = data;\t\t\r\n");
      out.write("\t\t\t\t\t\twindow.open(popUrl + \"/\" +  $num ,\"휴대폰 인증 \",popOption); \t\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror: function(xhr, status, err){\r\n");
      out.write("\t\t\t\t\t\tconsole.log(xhr);\r\n");
      out.write("\t\t\t\t\t\tconsole.log(status);\r\n");
      out.write("\t\t\t\t\t\tconsole.log(err);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}); \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function(){\r\n");
      out.write("\t\tvar key = getCookie(\"key\");\t\r\n");
      out.write("\t\tvar $memberId = $(\"#memberId_\").val(key);\r\n");
      out.write("\t\tvar $remember = $(\"#remember_\");\r\n");
      out.write("\r\n");
      out.write("\t\tif( $memberId != \"\"){\r\n");
      out.write("\t\t\t$remember.prop(\"checked\", true);\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$remember.prop(\"checked\", false)\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t$(\"#remember_\").change(function(){\r\n");
      out.write("\r\n");
      out.write("\t\t\tif($remember.is(\":checked\")){\r\n");
      out.write("\t\t\t\tsetCookie(\"key\", $(\"#memberId_\").val(), 7);\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tdeleteCookie(\"key\");\r\n");
      out.write("\t\t\t\t$remember.prop(\"checked\", false)\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$($memberId).keyup(function(){\r\n");
      out.write("\t\t\tif($remember.is(\":checked\")){\r\n");
      out.write("\t\t\t\tsetCookie(\"key\", $(\"#memberId_\").val(), 7);\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tdeleteCookie(\"key\");\r\n");
      out.write("\t\t\t\t$remember.prop(\"checked\", false)\r\n");
      out.write("\t\t\t}\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction setCookie(cookieName, value, exdays){\r\n");
      out.write("\t\tvar exdate = new Date();\r\n");
      out.write("\t\texdate.setDate(exdate.getDate() + exdays);\r\n");
      out.write("\r\n");
      out.write("\t\tvar cookieValue = escape(value) + ((exdays==null) ? \"\" : \"; expires=\" + exdate.toGMTString());\r\n");
      out.write("\t\tdocument.cookie = cookieName + \"=\" +cookieValue;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction deleteCookie(cookieName){\r\n");
      out.write("\t    var expireDate = new Date();\r\n");
      out.write("\t    expireDate.setDate(expireDate.getDate() - 1);\r\n");
      out.write("\t    document.cookie = cookieName + \"= \" + \"; expires=\" + expireDate.toGMTString();\r\n");
      out.write("\t}\r\n");
      out.write("\t \r\n");
      out.write("\tfunction getCookie(cookieName) {\r\n");
      out.write("\t    cookieName = cookieName + '=';\r\n");
      out.write("\t    var cookieData = document.cookie;\r\n");
      out.write("\t    var start = cookieData.indexOf(cookieName);\r\n");
      out.write("\t    var cookieValue = '';\r\n");
      out.write("\t    if(start != -1){\r\n");
      out.write("\t        start += cookieName.length;\r\n");
      out.write("\t        var end = cookieData.indexOf(';', start);\r\n");
      out.write("\t        if(end == -1)end = cookieData.length;\r\n");
      out.write("\t        cookieValue = cookieData.substring(start, end);\r\n");
      out.write("\t    }\r\n");
      out.write("\t    return unescape(cookieValue);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-md-3 col-md-offset-4\">\r\n");
      out.write("\t\t <ul class=\"nav nav-tabs\">\r\n");
      out.write("             <li class=\"active\"><a href=\"#member\" data-toggle=\"tab\">일반 회원</a></li>\r\n");
      out.write("             <li><a href=\"#adminTab\" data-toggle=\"tab\">관리자 회원</a></li>\r\n");
      out.write("         </ul>\r\n");
      out.write("          <div id=\"myTabContent\" class=\"tab-content\">\r\n");
      out.write("          <div class=\"tab-pane active in\" id=\"member\">\r\n");
      out.write("\t\t\t<div class=\"form\">\r\n");
      out.write("\t\t\t\t<form class=\"form\"\r\n");
      out.write("\t\t\t\t\taction=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/loginCheck.do\"\r\n");
      out.write("\t\t\t\t\tmethod=\"post\" id=\"login-form\">\r\n");
      out.write("\t\t\t\t\t<h3 class=\"heading-desc\">로그인</h3>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"memberId\" id=\"memberId_\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"아이디\" required autofocus />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" name=\"memberPWD\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"memberPWD_\" placeholder=\"비밀번호\" required />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<label class=\"checkbox\"> \r\n");
      out.write("\t\t\t\t\t\t<input type=\"checkbox\" name=\"remember\" id=\"remember_\"  /> 아이디저장\r\n");
      out.write("\t\t\t\t\t</label> \r\n");
      out.write("\t\t\t\t\t<a class=\"forgotLnk\" href=\"#\" class=\"btn btn-primary btn-lg\" data-toggle=\"modal\" data-target=\"#modalPassword\">비밀번호를 잊어 버리셨나요 ?</a>\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-lg btn-block purple-bg\" type=\"submit\">\r\n");
      out.write("\t\t\t\t\t\t로그인</button>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"or-box\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"or\"><h3>OR</h3></span>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 호근 수정 로그인버튼만 누르면 바로 연동되게 할 수 있게 수정  -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"center-block\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12 row-block\" id=\"naver_id_login\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"naver_id_login\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"social-login-btn social-facebook\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img width=\"50\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/naverLogo.jpg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"img-rounded\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 카카오 로그인 버튼 추가  -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"center-block\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12 row-block\" id=\"kakao_id_login\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"kakao_id_login\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"social-login-btn social-kakao\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ kakaoUrl }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img width=\"50\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/kakaolinkbtnsmall.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"img-rounded\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<!-- 구글 로그인 버튼 추가 -->\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"center-block\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12 row-block\" id=\"google_id_login\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"google_id_login\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"social-login-btn social-google\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ googleUrl }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<img width=\"50\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/images/googleL.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"img-rounded\" />\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"or-box row-block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12 row-block\" id=\"register-form-link\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn btn-lg btn-block purple-bg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t회원가입</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<!-- 회원가입 폼 추가 -->\r\n");
      out.write("\t\t\t\t<form id=\"register-form\"\r\n");
      out.write("\t\t\t\t\taction=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/memberEnroll.do\"\r\n");
      out.write("\t\t\t\t\tmethod=\"post\" role=\"form\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t<h3 class=\"heading-desc\">회원가입</h3>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"memberId\" id=\"memberId_\" tabindex=\"1\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\" placeholder=\"아이디를 입력해 주세요\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ snsMember.memberId != null ? snsMember.memberId : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write(' ');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ not empty snsMember ? \"readOnly\" : \"\" }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" name=\"memberPWD\" id=\"memberPWD_\" tabindex=\"2\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\" placeholder=\"비밀번호를 입력해주세요\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ snsMember.memberPWD != null ? snsMember.memberPWD : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write(' ');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ not empty snsMember ? \"readOnly\" : \"\" }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"password\" name=\"memberPWDCK\"\r\n");
      out.write("\t\t\t\t\t\t\tid=\"memberPWDCK_\" tabindex=\"2\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"비밀번호를 확인해주세요\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ snsMember.memberPWD != null ? snsMember.memberPWD : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write(' ');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ not empty snsMember ? \"readOnly\" : \"\" }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"memberName\" id=\"memberName_\" tabindex=\"1\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"form-control\" placeholder=\"이름을 입력해주세요\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ snsMember.memberName != null ? snsMember.memberName : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ not empty snsMember ? \"readOnly\" : \"\" }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-check form-check-inline\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" class=\"form-check-input\" name=\"gender\" id=\"gender0\" value=\"M\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ snsMember.gender eq  \"M\" ? \"checked readonly\" :\"\" }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t<label  class=\"form-check-label\" for=\"gender0\">남</label>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" class=\"form-check-input\" name=\"gender\" id=\"gender1\" value=\"F\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ snsMember.gender eq  \"F\" ? \"checked readonly\" :\"\" }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" >\r\n");
      out.write("\t\t\t\t\t\t<label  class=\"form-check-label\" for=\"gender1\">여</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"tel\" class=\"form-control\" \r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"(-없이)01012345678\" name=\"phone\" id=\"phone\" maxlength=\"11\" required>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-check form-check-inline\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" data-toggle=\"modal\" data-target=\".bs-example-modal-lg\"id=\"phone-send\">문자인증</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-6 col-sm-offset-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"btn btn-lg btn-block purple-bg\" type=\"submit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t가입하기</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"or-box row-block\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-12 row-block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" id=\"login-form-link\">이전 페이지</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- 관리자용 로그인 화면 -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t  <div class=\"tab-pane fade\" id=\"adminTab\">\r\n");
      out.write("                      <form id=\"adminTab\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ERP/erpLogin.do\" method=\"post\">\r\n");
      out.write("                     \t<h3 class=\"heading-desc\">관리자 로그인</h3>\r\n");
      out.write("                     \t<div class=\"form-group\">\r\n");
      out.write("\t                        <label for=\"empId_\">아이디</label>\r\n");
      out.write("\t                        <input type=\"text\" name=\"empId\" id=\"empId\" class=\"input-xlarge\">\r\n");
      out.write("\t                    </div>\r\n");
      out.write("\t                    <div class=\"form-group\">   \r\n");
      out.write("\t                        <label for=\"empPassword_\">비밀번호</label>\r\n");
      out.write("\t                        <input type=\"password\" name=\"empPwd\"  class=\"input-xlarge\">\r\n");
      out.write("                       \t</div>\r\n");
      out.write("                       \t<div class=\"form-check form-check-inline\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" class=\"form-check-input\" name=\"status\" id=\"status2\" value=\"2\" checked>\r\n");
      out.write("\t\t\t\t\t\t\t<label  class=\"form-check-label\" for=\"status2\">제조사</label>&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" class=\"form-check-input\" name=\"status\" id=\"status1\" value=\"1\" >\r\n");
      out.write("\t\t\t\t\t\t\t<label  class=\"form-check-label\" for=\"status1\">지점</label>\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"radio\" class=\"form-check-input\" name=\"status\" id=\"status0\" value=\"0\" >\r\n");
      out.write("\t\t\t\t\t\t\t<label  class=\"form-check-label\" for=\"status0\">본사</label>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("                        <div>\r\n");
      out.write("                          <button type=\"submit\" class=\"btn btn-primary\">로그인</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 비밀번호 찾기용 모달 창 -->\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footerS.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
